# Generated by Django 3.2.6 on 2021-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpage',
            name='rogers_doc_title',
            field=models.CharField(max_length=230, null=True),
        ),
    ]
