# Generated by Django 3.2.6 on 2021-08-08 19:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicpage_rogers_doc_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='academicpage',
            name='rogers_doc_subtitle',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
