# Generated by Django 3.2.6 on 2021-08-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20210808_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicpage',
            old_name='rogers_doc_title',
            new_name='doc_title',
        ),
        migrations.RenameField(
            model_name='academicpage',
            old_name='rogers_doc_subtitle',
            new_name='subtitle',
        ),
    ]
