# Generated by Django 3.2.5 on 2021-07-27 08:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210727_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bio',
            field=wagtail.core.fields.StreamField([('bio_data', wagtail.core.blocks.StructBlock([('first_name', wagtail.core.blocks.CharBlock(help_text='First Name', required=True)), ('last_name', wagtail.core.blocks.CharBlock(help_text='Last Name', required=True)), ('bio_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('role', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('role', wagtail.core.blocks.StructBlock([], max_length=20, required=True))])))]))], null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='persoanl_data',
            field=wagtail.core.fields.StreamField([('personal_data_info', wagtail.core.blocks.StructBlock([('data', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('residence', wagtail.core.blocks.CharBlock(max_length=15, required=True)), ('city', wagtail.core.blocks.CharBlock(max_length=15, required=True)), ('age', wagtail.core.blocks.CharBlock(max_length=2, required=True))]))), ('language', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('lang', wagtail.core.blocks.CharBlock(max_length=15, required=True))]))), ('programming', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('programming_language', wagtail.core.blocks.CharBlock(max_length=20, required=True))])))]))], null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='records',
            field=wagtail.core.fields.StreamField([('record_data', wagtail.core.blocks.StructBlock([('records', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('record', wagtail.core.blocks.CharBlock(max_length=20, required=True)), ('period', wagtail.core.blocks.CharBlock(max_length=3, required=True))])))]))], blank=True, null=True),
        ),
    ]
