# Generated by Django 3.2.5 on 2021-07-27 09:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210727_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='price_plan',
            field=wagtail.core.fields.StreamField([('plans', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=15, required=True)), ('plans', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('pan_type', wagtail.core.blocks.CharBlock(required=True)), ('pan_subtitle', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('item_name', wagtail.core.blocks.CharBlock(required=True))]))), ('button_url', wagtail.core.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service',
            field=wagtail.core.fields.StreamField([('myservice', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=20, required=True)), ('my_services', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('service', wagtail.core.blocks.CharBlock(max_length=30, required=True)), ('descript', wagtail.core.blocks.CharBlock(max_length=150, required=True)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))])))]))], blank=True, null=True),
        ),
    ]
