# Generated by Django 3.2.5 on 2021-07-27 10:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210727_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='organi',
            field=wagtail.core.fields.StreamField([('Organisations', wagtail.core.blocks.StructBlock([('org', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('Photo', wagtail.images.blocks.ImageChooserBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
