# Generated by Django 3.2.5 on 2021-07-27 10:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_organi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='organi',
        ),
        migrations.AddField(
            model_name='homepage',
            name='organisations',
            field=wagtail.core.fields.StreamField([('organi', wagtail.core.blocks.StructBlock([('organisation', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('Photo', wagtail.images.blocks.ImageChooserBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
