# Generated by Django 3.2.5 on 2021-07-27 10:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210727_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='organisations',
        ),
        migrations.AddField(
            model_name='homepage',
            name='organisations_logo',
            field=wagtail.core.fields.StreamField([('Organisations', wagtail.core.blocks.StructBlock([('organisation', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('Photo', wagtail.images.blocks.ImageChooserBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
