# Generated by Django 3.2.6 on 2021-08-05 09:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0009_auto_20210727_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title_two',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bio',
            field=wagtail.core.fields.StreamField([('bio_data', wagtail.core.blocks.StructBlock([('first_name', wagtail.core.blocks.CharBlock(help_text='First Name', required=True)), ('last_name', wagtail.core.blocks.CharBlock(help_text='Last Name', required=True)), ('bio_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('role', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('role', wagtail.core.blocks.CharBlock(max_length=20, required=True)), ('email', wagtail.core.blocks.EmailBlock(required=True))])))]))], null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='persoanl_data',
            field=wagtail.core.fields.StreamField([('personal_data_info', wagtail.core.blocks.StructBlock([('data', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('residence', wagtail.core.blocks.CharBlock(max_length=15, required=True)), ('city', wagtail.core.blocks.CharBlock(max_length=15, required=True)), ('age', wagtail.core.blocks.IntegerBlock(max_value=20))]))), ('language', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.CharBlock(max_length=15, required=True))]))), ('programming', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('programming_language', wagtail.core.blocks.CharBlock(max_length=20, required=True))])))]))], null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='recommend',
            field=wagtail.core.fields.StreamField([('Recommendations', wagtail.core.blocks.StructBlock([('recommendations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('Name', wagtail.core.blocks.CharBlock(max_length=45, required=True)), ('Job_Title', wagtail.core.blocks.CharBlock(max_length=45, required=True)), ('Photo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('Stament', wagtail.core.blocks.CharBlock(max_length=45, required=True)), ('star', wagtail.core.blocks.IntegerBlock(max_value=5))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='records',
            field=wagtail.core.fields.StreamField([('record_data', wagtail.core.blocks.StructBlock([('records', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('record', wagtail.core.blocks.CharBlock(max_length=20, required=True)), ('period', wagtail.core.blocks.IntegerBlock(max_value=20))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service',
            field=wagtail.core.fields.StreamField([('myservice', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=20, required=True)), ('my_services', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('service', wagtail.core.blocks.CharBlock(max_length=30, required=True)), ('description', wagtail.core.blocks.CharBlock(max_length=150, required=True)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))])))]))], blank=True, null=True),
        ),
    ]
