# Generated by Django 3.2.6 on 2021-08-05 20:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210805_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='bio',
            field=wagtail.core.fields.StreamField([('bio_data', wagtail.core.blocks.StructBlock([('first_name', wagtail.core.blocks.CharBlock(help_text='First Name', required=True)), ('last_name', wagtail.core.blocks.CharBlock(help_text='Last Name', required=True)), ('bio_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('role', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('my_role', wagtail.core.blocks.CharBlock(max_length=20, required=True)), ('email', wagtail.core.blocks.EmailBlock(required=True))])))]))], null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='persoanl_data',
            field=wagtail.core.fields.StreamField([('personal_data_info', wagtail.core.blocks.StructBlock([('data', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('residence', wagtail.core.blocks.CharBlock(max_length=15, required=True)), ('city', wagtail.core.blocks.CharBlock(max_length=15, required=True)), ('age', wagtail.core.blocks.IntegerBlock(max_value=20))]))), ('language', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.CharBlock(max_length=15, required=True)), ('rating', wagtail.core.blocks.IntegerBlock(max_value=100))]))), ('programming', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('programming_language', wagtail.core.blocks.CharBlock(max_length=20, required=True)), ('rating', wagtail.core.blocks.IntegerBlock(max_value=100))]))), ('framework', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('my_framework', wagtail.core.blocks.CharBlock(max_length=20, required=True)), ('rating', wagtail.core.blocks.IntegerBlock(max_value=100))]))), ('additional_skills', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('addtional_skils', wagtail.core.blocks.CharBlock(max_length=20, required=True))])))]))], null=True),
        ),
    ]
