# Generated by Django 3.2.6 on 2021-08-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210805_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='records',
            new_name='my_records',
        ),
    ]
