# Generated by Django 3.2.6 on 2021-08-13 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_alter_portfolio_lincense_and_certificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortFolio',
            new_name='PortFolioPage',
        ),
    ]
